# Generated by Django 6.0.7 on 2026-08-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('highlight_text', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button1_text', models.CharField(blank=True, max_length=100)),
                ('button1_url', models.CharField(blank=True, max_length=255)),
                ('button2_text', models.CharField(blank=True, max_length=100)),
                ('button2_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='hero_sliders/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='hero_sliders/mobile/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
