# Generated by Django 6.0.7 on 2026-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
