# Generated by Django 6.0.7 on 2026-08-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_status_order_razorpay_order_id_and_more'),
        ('products', '0003_productpricevariation_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productpricevariation'),
        ),
    ]
