# Generated by Django 6.0.7 on 2026-08-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricevariation',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Available stock quantity', max_digits=12),
        ),
        migrations.AddField(
            model_name='productpricevariation',
            name='stock_unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'Gram'), ('pcs', 'Pieces'), ('bunch', 'Bunch'), ('pack', 'Pack'), ('box', 'Box')], default='kg', max_length=20),
        ),
    ]
